export const navbarData = [
  {
    ruta: 'home',
    nombre: 'Dashboard',
    icon: 'fas fa-tachometer-alt',
    permisos: [
      'superadmin',
      'Gestor de Puntos de Venta',
      'Coordinador de Servicios',
    ],
    pas: false,
  },
  {
    ruta: 'users-admin',
    nombre: 'Usuarios',
    icon: 'fas fa-users',
    permisos: ['superadmin'],
    pas: false,
  },
  {
    ruta: 'points-of-sales-admin',
    nombre: 'Puntos de Venta',
    icon: 'fas fa-store',
    permisos: ['superadmin', 'Gestor de Puntos de Venta'],
    pas: false,
  },
  {
    ruta: 'services-admin',
    nombre: 'Servicios',
    icon: 'fas fa-concierge-bell',
    permisos: ['superadmin', 'Coordinador de Servicios'],
    pas: false,
  },
  {
    ruta: 'testimonios-admin',
    nombre: 'Testimonios',
    icon: 'fas fa-comments',
    permisos: ['superadmin'],
    pas: false,
  },
  {
    ruta: 'bioproducts-admin',
    nombre: 'Bioproductos',
    icon: 'fas fa-seedling',
    permisos: ['superadmin'],
    pas: false,
  },
  {
    ruta: 'contacts-admin',
    nombre: 'Contactos',
    icon: 'fas fa-address-book',
    permisos: ['superadmin'],
    pas: false,
  },
  {
    ruta: '/home',
    nombre: 'Salir',
    icon: 'fas fa-sign-out-alt',
    permisos: [
      'superadmin',
      'Gestor de Puntos de Venta',
      'Coordinador de Servicios',
    ],
    pas: false,
  },
];
